@echo ""
@echo " Mac Mini Firmware Menu"
@echo " Type your board number, then press return:-"
@echo ""
@echo "A1347 820-5509   - FW: 2.24f32  -  Type: 820-5509.nsh"
@echo ""
@echo "Type 'startup.nsh' to go back."
@echo ""
@echo "NOTE: Script will run immediately, so be sure"
@echo "      when you choose to run the script."
@echo ""