@echo ""
@echo "SMCTool V1.0.6 by David R (Muerto)"
@echo ""
@echo " Type your device name, then press return:-"
@echo ""
@echo "MacBook  -  Type: macbook.nsh"
@echo "MacMini  -  Type: macmini.nsh"
@echo "iMac     -  Type: imac.nsh"
@echo ""
@echo "Type 'reset' at any time to poweroff."
@echo ""
